### ISSUE TITLE
support for slider

### ISSUE THREAD

**Issue by ramarro123** [tilwinjoy/angular-bootstrap-material#2]
Hello,

any plan to support slider from bootstrap material ui?

**Comment by tilwinjoy** [comment]
Hi, The slider in bootstrap material is based on [noUiSlider](http://refreshless.com/nouislider/).
We just need a wrapper angular directive to support it<sup>*</sup>. Luckily, those already exist. for example - [nouislider-angular](https://github.com/Yankovsky/nouislider-angular).

Here's a [**JSFiddle demo**](https://jsfiddle.net/e1pLrxg1/1) that I made using the same.

---

*I'm not including it as part of this project since other projects for supporting noUiSlider with AngularJS already exist. Also because it's neither a Bootstrap component nor I have seen it in Google material spec.

**Comment by ramarro123** [comment]
great, if so, no need to add it on your side :)
