### ISSUE TITLE
form support in 2 row

### ISSUE THREAD

**Issue by ramarro123** [tilwinjoy/angular-bootstrap-material#4]
i am trying to make a fluid layout for a form, with 2 row element that collapse to a single row when col-xs is reached

that's what i have do

```
                <abm-form-group class="form-group">
                    <label class="col-xs-2 col-sm-2 control-label">Alba</label>
                    <div class="col-xs-10 col-sm-4">
                        <timepicker-pop input-name="alba" class="input-group"
                                        input-time="main.settings_save.alba"
                                        show-meridian='false'></timepicker-pop>
                    </div>
                </abm-form-group>

                <abm-form-group class="form-group">
                    <label class="col-xs-2 col-sm-2 control-label">Tramonto</label>
                    <div class="col-xs-10 col-sm-4">
                        <timepicker-pop input-name="tramonto" class="input-group"
                                        input-time="main.settings_save.tramonto"
                                        show-meridian='false'></timepicker-pop>
                    </div>
                </abm-form-group>

```

now, if i put col-md-6 on abm-form-group
it will 'work' but the second row (that's just a single row)
will 'cover' the first one and i am not able to gain focus on the row.

if i put a div class='row' element, it won't pad using bootstrap standard padding.

previously, using just boostrap i use
<div class=form-group col-xs-12>
but seems that on adb-form-group i can't do that, it cover the div, as said.

**Comment by tilwinjoy** [comment]
Hi, The `abm-form-group` directive is supposed to be used with other `abm-*` directives. If you're using something else, then no need to use it. It won't make any difference unless you require `abm-form-group` inside your custom directive an use the API it provides .

 The issue is probably caused by the `timepicker-pop` component you're using and is specific to you. Please create a minimal demo as mentioned in [contribution guidelines](https://github.com/tilwinjoy/angular-bootstrap-material/blob/master/CONTRIBUTING.md#bug-reports) without using any custom directives and css. If it's caused by custom directives/css, please post as a question in Stack Overflow as mentioned in [contribution guidelines](https://github.com/tilwinjoy/angular-bootstrap-material/blob/master/CONTRIBUTING.md#using-the-issue-tracker)
